"""Add note field to Order

Revision ID: 5d7ed75fd403
Revises: a2ae6abbaeec
Create Date: 2025-07-22 19:55:47.058991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7ed75fd403'
down_revision = 'a2ae6abbaeec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
