"""Renamed note to order_description, added company_name, location, email

Revision ID: ad30494ece95
Revises: 5d7ed75fd403
Create Date: 2025-07-28 13:52:34.273851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad30494ece95'
down_revision = '5d7ed75fd403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.drop_column('note')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('location')
        batch_op.drop_column('company_name')
        batch_op.drop_column('order_description')

    # ### end Alembic commands ###
